### ISSUE TITLE
Rails Console Fails: Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)

### ISSUE THREAD

**Issue by toddmichael** [jamtur01/aom-rails#1]
Loving the book so far @jamtur01.  Thanks for writing it!  My assumption was that I could follow along with the monitoring exercise by cloning this sample application, but it fails due to missing database configuration file which is `.gitignore`d.  Any advice on how to continue following along is appreciated.

**Comment by jamtur01** [comment]
That looks like a default `.gitignore` oversight. Added in the configuration files. Thanks!

**Comment by toddmichael** [comment]
Thanks mate.  I'm back in business.
```
$ rails c
Loading development environment (Rails 4.2.4)
[1] pry(main)>
```
Cheers.
